### PR TITLE
compile on scala 2.12.1, remove hdf5 from the core build, update test…

### PR DESCRIPTION
**Pull request by pityka**
… dependencies

### CODE REVIEW

**Comment by pityka** [comment]
Travis has java version problems. "java.lang.UnsupportedClassVersionError: scala/tools/nsc/Main : Unsupported major.minor version 52.0"

**Comment by hntd187** [comment]
@pityka gonna wanna run against the jdk8 on travis since I believe it's 7 by default. should be able to add something like https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs to test against only the openjdk8

**Comment by pityka** [comment]
Travis has oraclejdk8. Otherwise seems to be good now.

**Comment by hntd187** [comment]
One final nit pick, can we change 2.10.5 to 2.10.6 that's the latest and I believe the final version of the 2.10 line

**Comment by hntd187** [comment]
Awesome @pityka thanks!

**Pull request merged**
